export enum TAG_TYPES {
  user = "user",
  department = "department",
  student = "student",
  faculty = "faculty",
  admin = "admin",
  academicFaculty = "academic-faculty",
  academicDepartment = "academic-department",
  academicSemester = "academic-semester",
  building = "building",
  room = "room",
  course = "course",
  semesterRegistration = "semester-registration",
  offeredCourse = "offered-course",
  offeredCourseSection = "offered-course-section",
  offeredCourseSchedule = "offered-course-schedule",
  courseRegistration = "course-registration",
}

export const tagTypesList = [
  TAG_TYPES.user,
  TAG_TYPES.department,
  TAG_TYPES.student,
  TAG_TYPES.faculty,
  TAG_TYPES.admin,
  TAG_TYPES.academicFaculty,
  TAG_TYPES.academicDepartment,
  TAG_TYPES.academicSemester,
  TAG_TYPES.building,
  TAG_TYPES.room,
  TAG_TYPES.course,
  TAG_TYPES.semesterRegistration,
  TAG_TYPES.offeredCourse,
  TAG_TYPES.offeredCourseSection,
  TAG_TYPES.offeredCourseSchedule,
  TAG_TYPES.courseRegistration,
];
